version: '3.8'
services:
    web:
        image: discord
        build: .
        command: "node discord"
        ports : 
            - "3030:3030"
        depends_on:
            - "go-monitors"
    go-monitors:
        image: "go-monitors"
        build: "./GoMonitor"
        command: "go run main.go"
        ports : 
            - "7243:7243"